server.port : 8009
management.endpoints.web.exposure.include: '*'
spring:
  application:
    name: spring-config-jdbc-client
  datasource:
    url: jdbc:mysql://localhost:3306/sys
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: root
    hikari:
      connection-timeout: 5000
      maximum-pool-size: 10
  profiles:
    active: jdbc,dev

  config:
#    import=configserver:
    import: optional:configserver:http://localhost:8888
  cloud:
    config:
#      uri: http://localhost:8888
      label: 1.1
      profile: dev
      import-check:
        enabled: false

    bus:
      enabled: true
      refresh:
        enabled: true
app:
  config:
    configA: ConfigA - static
    configB: ConfigB - static
    configC: ConfigC - static
    configD: ConfigD - static

scheduler:
  interval: 10000
  enabled: false

#      Add a spring.config.import=configserver: property to your configuration.
#        If configuration is not required add spring.config.import=optional:configserver: instead.
#        To disable this check, set spring.cloud.config.enabled=false or
#        spring.cloud.config.import-check.enabled=false.